// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7FuGwkcltE8ZyOD6-0lNAbrxsMQvB3mQ',
    appId: '1:724685788701:android:7c7fed1653dc378cbd18f4',
    messagingSenderId: '724685788701',
    projectId: 'adhd-0-1',
    storageBucket: 'adhd-0-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88rpy-0bs6t_F40-2VINwavfN-nQ44eQ',
    appId: '1:724685788701:ios:04c0074688fbc5f4bd18f4',
    messagingSenderId: '724685788701',
    projectId: 'adhd-0-1',
    storageBucket: 'adhd-0-1.firebasestorage.app',
    iosBundleId: 'com.example.adhd01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA88rpy-0bs6t_F40-2VINwavfN-nQ44eQ',
    appId: '1:724685788701:ios:04c0074688fbc5f4bd18f4',
    messagingSenderId: '724685788701',
    projectId: 'adhd-0-1',
    storageBucket: 'adhd-0-1.firebasestorage.app',
    iosBundleId: 'com.example.adhd01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTrOSHBTIXd-aYCKe_F0M4X0kDKDK4vH0',
    appId: '1:724685788701:web:36dd1d6ed4417fa0bd18f4',
    messagingSenderId: '724685788701',
    projectId: 'adhd-0-1',
    authDomain: 'adhd-0-1.firebaseapp.com',
    storageBucket: 'adhd-0-1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTrOSHBTIXd-aYCKe_F0M4X0kDKDK4vH0',
    appId: '1:724685788701:web:36dd1d6ed4417fa0bd18f4',
    messagingSenderId: '724685788701',
    projectId: 'adhd-0-1',
    authDomain: 'adhd-0-1.firebaseapp.com',
    storageBucket: 'adhd-0-1.firebasestorage.app',
  );

}