const List<String> tipOfTheDay = [
  "Discipline is hot, mediocrity is boring. Become ungovernable.",
  "Discipline is hot, mediocrity is boring. Get dramatic with your ambition.",
  "Discipline is hot, mediocrity is boring. Pretend you're in a montage.",
  "Discipline is hot, mediocrity is boring. Today owes you nothing. Take it anyway.",
  "Be the glitch in the matrix.",
  "Discipline is hot now — and that's a you problem. Become someone your ex fears.",
  "Discipline is hot now — and that's a you problem. Conquer something today.",
  "Do it for the plot.",
  "It's a Tuesday, not a crisis. Pretend you're in a montage.",
  "Silence the inner hater. Become ungovernable.",
  "Silence the inner hater. Unleash main character energy.",
  "That's just the Wi-Fi talking. Today owes you nothing.",
  "Get dramatic with your ambition.",
  "Unleash main character energy.",
  "It's your comfort zone whispering.",
  "It's your comfort zone whispering. Get mad, then get moving.",
  "It's your dopamine addiction. Be the glitch in the matrix.",
  "It's your dopamine addiction. Become ungovernable.",
  "It's your fear of failure. Become ungovernable.",
  "It's your fear of failure. Unleash main character energy.",
  "Silence the inner hater. Be the glitch in the matrix.",
  "Silence the inner hater. Get mad.",
  "Silence the inner hater. Unleash main character energy.",
  "Nobody is coming to save you — and mediocrity is boring.",
  "Become ungovernable.",
  "Nobody is coming to save you — and that's a you problem.",
  "Nobody is coming to save you — Unleash main character energy.",
  "Nobody is coming to save you — Be the glitch in the matrix.",
  "Nobody is coming to save you.",
  "Nobody is coming to save you — Conquer something today.",
  "It's a Tuesday, not a crisis. Become someone your ex fears.",
  "It's a Tuesday, not a crisis. Do it for the plot.",
  "Nobody is coming to save you — it's just inertia. Be the glitch in the matrix.",
  "Nobody is coming to save you — it's just inertia. Become someone your ex fears.",
  "It's just inertia. Become ungovernable.",
  "It's your comfort zone whispering. Become ungovernable.",
  "It's your dopamine addiction.",
  "Today owes you nothing.",
  "Outrun your past like it owes you money.",
  "You're not lazy, just too creative for mundane tasks.",
  "Wake up. Choose chaos. Organize it.",
  "Doubt is just a squatter in your brain—evict it.",
  "If they call you extra, charge them interest.",
  "You're not behind; you're in stealth mode.",
  "Get up and scare your potential into action.",
  "Your comfort zone called—it's getting evicted.",
  "Burnout isn't a trophy. Work smart, not to ashes.",
  "Slay your to-do list like it insulted your dog.",
  "Rise and shine? Nah. Rise and conquer.",
  "Be a menace to mediocrity.",
  "A plan is just rebellion with a calendar.",
  "Don't chase dreams—ambush them.",
  "Your future self is watching. Don't disappoint her.",
  "Perfection is a scam. Be consistently weird instead.",
  "Ignore the noise. Build your empire quietly.",
  "Monday blues? Paint it neon.",
  "Be the glitch in the matrix — on purpose.",
  "The limit isn't the sky. It's your Wi-Fi.",
  "Your vibe is the resume the universe reads.",
  "Break the cycle, not your spirit.",
  "Go feral—but with a spreadsheet.",
  "One person's 'too much' is another's inspiration.",
  "Grind like you're trying to escape a simulation.",
  "If it scares you, it might just be the way.",
  "Feral productivity starts with one unhinged to-do list.",
  "Delusional confidence is just confidence that hasn't been proven right yet.",
  "You don't need a plan. You need caffeine and vibes.",
  "You're not procrastinating—you're incubating brilliance.",
  "Become ungovernable. Start by making your bed.",
  "Why fit in when you can disrupt the entire ecosystem?",
  "Your chaos is your competitive advantage.",
  "You woke up today. That's the first victory. Now go commit a few more.",
  "Be the glitch in the system you want to see in the world.",
  "Productivity tip: pretend you're the main character in a redemption arc.",
  "Everything is made up and you can do what you want—within reason. Or not.",
  "Revenge arc starts now. Step one: hydrate.",
  "Your goals are scared of you. Good. Chase them anyway.",
  "You're one slightly unhinged idea away from greatness.",
  "Ignore the rules. Make your own. Break those too.",
  "Confidence isn't real. But act like it is until it becomes contagious.",
  "Stay soft. Destroy everything anyway.",
  "Your vibe today? Controlled chaos with high output.",
  "You are the storm in your own weather app.",
  "You're not behind. You're just charging up for a dramatic entrance.",
  "There are no stupid questions, only stupid people.",
  "Your potential didn't ghost you — it's just waiting for a plot twist.",
  "The algorithm isn't against you. You're just not weird enough yet.",
  "Chaos isn't a flaw. It's your creative process going off-script.",
  "Build your legacy like it's an indie game and you're the only coder.",
  "You've got main character energy. Stop handing it out like coupons.",
  "Dreams are cute. Action is hot.",
  "Messy progress is still progress. Leave perfection to the robots.",
  "Run your day like it's a startup and you're the last employee standing.",
  "Forget hustle culture. Try unhinged precision instead.",
  "You're not procrastinating — you're buffering brilliance.",
  "The best revenge arc starts with an early alarm.",
  "Your ambition isn't too big — your environment is too small.",
  "Today's crisis is just a subplot. Power through.",
  "Audacity is a strategy, not a personality flaw.",
  "Go the extra mile — it's usually deserted and quiet enough to think.",
  "Your fear of failure is just nostalgia for your comfort zone.",
  "Wake up and disrupt the timeline.",
  "Delulu but effective. That's the vibe.",
  "Stability is a scam. Make the leap.",
  "The vibe today: spreadsheet feral with a side of menace.",
  "What if the thing holding you back is just a bad Wi-Fi signal?",
  "Low energy? High standards. Move anyway.",
  "You're not messy — you're just in beta mode.",
  "Give your future self something to brag about.",
  "Success isn't a mood — it's a muscle. Flex it.",
  "Be the unskippable ad in someone's day.",
  "You're not lost. You're just off the main trail building something better.",
  "Don't manifest. Build.",
  "You're not tired — you're under-stimulated. Go scare your comfort zone.",
  "Every task is a battle. Win on vibes and caffeine.",
  "Schedule your existential crisis — then go execute the plan.",
  "Stop asking permission. You're not a pop-up ad.",
  "You're not burnt out. You're bored. Go do something ridiculous.",
  "Ambition isn't toxic. Suppression is.",
  "Quit apologizing for your drive. Some people nap through life.",
  "Your sabotage isn't sexy. Try consistency for once.",
  "Mood: Focused chaos with aesthetic flair.",
  "Your comfort zone has no Wi-Fi. Get out.",
  "Monday? More like boss level unlocked.",
  "You weren't born to be realistic. Be legendary instead.",
  "Forget clarity — take action and aim mid-flight.",
  "You're not 'too much' — you're future-proofed.",
  "Procrastination is just passion misdirected.",
  "You don't need a roadmap. You need ignition.",
  "No one asked you to be perfect. Just powerful.",
  "Crisis is inevitable. Collapse is optional.",
  "Delete 'what if'. Replace with 'watch this.'",
  "Multitask like a chaotic genius with a villain arc.",
  "You're not being ignored — you're just ahead of your time.",
  "Your weird idea? That's the strategy.",
  "You didn't wake up today to stay mediocre.",
  "Hard work beats talent when talent keeps checking Instagram.",
  "You don't lack motivation — you lack dragons to slay.",
  "You're not unmotivated — you're under-mythologized.",
  "Productivity is a side effect of obsession.",
  "Focus like the world is background noise.",
  "Delete the app. Build the empire.",
  "Don't climb the ladder — duct tape a jetpack.",
  "Anxiety isn't weakness. It's fuel. Use it.",
  "Your fear is valid. It's also irrelevant.",
  "Self-doubt doesn't pay rent. Evict it.",
  "You are the niche. Be loud about it.",
  "Don't seek balance. Seek combustion.",
  "You are not the underdog. You are the threat.",
  "Consistency is king. Chaos is the crown.",
  "Change your algorithm. Start with your habits.",
  "Make moves so big they show up on satellite.",
  "Ignore trends. Set fires.",
  "Build discipline like it's a rebellion.",
  "Comfort is addictive. So is success. Pick one.",
  "You're not behind — you're loading.",
  "Start before you're ready. Ready is a myth.",
  "Your next win is hiding behind your next discomfort.",
  "You're not overwhelmed — you're upgrading.",
  "You don't need motivation. You need motion.",
  "Every excuse is a vote for your old self.",
  "You don't need to feel like it. You need to do it.",
  "Turn imposter syndrome into performance fuel.",
  "Rejection is redirection wearing a scary hat.",
  "Main character energy requires main character decisions.",
  "You're the plot device now.",
  "Go fail harder. It means you're closer.",
  "Replace guilt with growth. Start small.",
  "Schedule fear after execution.",
  "Mastery isn't talent. It's stubbornness refined.",
  "Your comfort zone is a nice place to rot.",
  "The grind isn't aesthetic. Make it worth it.",
  "You're not lost. You're iterating.",
  "Discipline isn't punishment. It's self-respect with a planner.",
  "Every 'no' is fertilizer for a better yes.",
  "Uncertainty is your co-pilot. Buckle up.",
  "Be so consistent you bore your distractions.",
  "Obsession isn't crazy. It's focused fire.",
  "Quit romanticizing quitting.",
  "Go full tilt. Burn the safety net.",
  "You're not a perfectionist. You're just scared.",
  "Rest isn't a reward. It's part of the rebellion.",
  "Try failing fast and failing forward — it's efficient rebellion.",
  "Ditch motivation. Build momentum.",
  "Don't adapt. Outgrow.",
  "Forget mood. Respect mission.",
  "You don't lack vision. You lack urgency.",
  "Play the long game. But sprint today.",
  "Quit optimizing for approval. Optimize for output.",
  "Rip the bandaid. Build the empire. Cry later.",
  "You are the glitch. The app crash. The cosmic reroute.",
  "Hustle like you just found out you're not real.",
  "The vibes are unstable. Capitalize on that.",
  "Rebrand your breakdown as character development.",
  "Be so chaotic they can't auto-moderate you.",
  "Take the leap — scream on the way down.",
  "Today is a speedrun. Fail faster.",
  "Burnout is cringe. Rage-rest-repeat.",
  "Why wait for a sign when you can throw one?",
  "You don't need a plan. You need a disruption.",
  "Snooze buttons are for side characters.",
  "Prove them wrong with results, not paragraphs.",
  "Life's a simulation — might as well break the UI.",
  "It's not overthinking if you monetize it.",
  "Eat the frog. Then eat the task list.",
  "Organize your chaos like it's art.",
  "Overwhelmed? Good. That means you're evolving.",
  "Reality is lagging. Move like it's caught up.",
  "If you're not spiraling at light speed, are you even trying?",
  "Ditch inner peace. Build external dominance.",
  "This isn't discipline. It's a controlled spiral upward.",
  "Who needs clarity? You've got raw intent.",
  "Today is brought to you by: caffeine and vengeance.",
  "Delete your doubts. Force quit your fear.",
  "Your power is glitching. Reboot with intent.",
  "Act like you've already succeeded — confuse the simulation.",
  "Your villain origin story needs tighter deadlines.",
  "Productivity tip: pretend it's a heist.",
  "Chaos isn't the enemy. Boredom is.",
  "Sprint like the floor is lava and failure is catching up.",
  "You're not too much. You're just properly scaled.",
  "You are the boss fight someone else is avoiding.",
  "Anxiety's in the room. Make it take notes.",
  "Don't keep it together. Keep it moving.",
  "Forget tidy. Be unstoppable.",
  "Schedule your spiral after your success.",
  "If the system hates you, build your own software.",
  "You're the assignment. And you're due today.",
  "It's a full-send kind of day.",
  "Wake up, choose delusion, conquer everything.",
  "You're not allowed to quit without making noise first.",
  "Build it wrong. Rebuild it better. Keep going.",
  "Act like your future self is live-streaming this.",
  "The only red flag here is hesitation.",
  "Fear is a consultant. You don't have to take the advice.",
  "Every undone task is a dare. Accept them all.",
  "You are not optional. Start acting like it.",
  "You don't lack vision. You're just stuck in debug mode.",
  "Why pause when you can pivot violently?",
  "Work like your enemies are spectating.",
  "Stay soft. Burn everything anyway.",
  "Forget the strategy deck — go full narrative arc.",
  "Unfinished doesn't mean failed. It means in-progress rage.",
  "Let your habits be louder than your breakdowns.",
  "Reframe your meltdown as data collection.",
  "You're not spiraling. You're speed-processing.",
  "Set your standards so high they need oxygen masks.",
  "If it's easy, you're doing it wrong. Or worse — mediocre.",
  "Try reckless focus. You'll like it.",
  "Your to-do list thinks it's winning. Prove it wrong.",
  "Reality check: you're underutilized chaos.",
  "Be the bug in the system, not the user error.",
  "Go full tilt with a power stance.",
  "Your inner hater called — they're unemployed now.",
  "You're not a mess. You're mid-transformation.",
  "Be brave enough to suck at it loudly.",
  "You have 24 hours. Pretend it's a countdown.",
  "If you're comfortable, you're coasting.",
  "Scream internally. Execute externally.",
  "You're a late bloomer? Good. That means explosions are next.",
  "Default settings don't suit you.",
  "Let your ambition be a public disturbance.",
  "You are the loophole. Exploit yourself wisely.",
  "You can't ghost your destiny. It has your IP.",
  "Success isn't cute. It's gritty and inconvenient. Keep going.",
  "The glow-up is mental. Light yourself up.",
  "Plot twist: it was your era all along.",
  "Finish something. Anything. Then get unhinged again.",
  "You don't need healing. You need movement.",
  "You're not unmotivated. You're under-chaosed.",
  "Outrun the algorithm. Outwork the past.",
  "There is no plan B. Just more A in weird fonts.",
  "You're one breakdown away from your breakthrough. Speed it up.",
  "Mastery is repetition + disrespect for limits.",
  "Your mission is bigger than your mood.",
  "Small steps? Nah. Leap and regenerate.",
  "You weren't made for peace. You were made for impact.",
  "You're not over it — you're overdue.",
  "Channel your rage into progress bars.",
  "You're not tired. You're under-rebellious.",
  "Fail fast, fail forward, fail fabulous.",
  "The moment is unstable — capitalize.",
  "You don't need a new mindset. You need a new battlefield.",
  "Every day you delay is a day the plot stalls.",
  "Write your to-do list in all caps. Then obey it like a spell.",
  "If it's scary, chase it. If it's boring, destroy it.",
  "You're not busy. You're brewing.",
  "The next level won't wait. Neither should you.",
  "Abandon the script. Rewrite the genre.",
  "You're not stuck — you're buffering rage into results.",
  "Burn the blueprint. Use the ashes to draw new battle lines.",
  "Plan? No. We're doing prophecy today.",
  "High-functioning disaster? Weaponize it.",
  "Turn your to-do list into a hit list. Execute accordingly.",
  "Let your ambition be unsettling. That's how you know it's working.",
  "You're not overthinking. You're conjuring.",
  "Your shadow self wants in. Hand it the calendar.",
  "Have you tried chaos in moderation? Me neither.",
  "The anxiety is here — assign it a task.",
  "Collapse in style, then get up louder.",
  "You're the final boss of your own avoidance.",
  "Act like your enemies are watching. Because they are.",
  "The real glow-up is organized vengeance.",
  "If you're spiraling, do it with bullet points.",
  "Some days you're the storm. Some days you're the alarm system failing.",
  "Make your procrastination afraid of you.",
  "You're not procrastinating — you're staging a coup on your comfort.",
  "Let failure flirt with you. Then ghost it mid-sentence.",
  "You don't need rest — you need a dramatic soundtrack.",
  "This isn't a task. It's a summoning ritual.",
  "Disorder is just creativity warming up.",
  "Your focus is feral. Don't tame it — direct it.",
  "Don't 'manage' time. Beat it into submission.",
  "You are the red flag HR warned about. Keep building.",
  "Overwhelm is your origin story. Keep writing it.",
  "If you can't fix it, haunt it.",
  "Deadlines aren't scary. Regret is.",
  "Your success doesn't need permission. Just better fonts.",
  "The goal isn't peace. The goal is domination with kindness.",
  "Keep it cute. Keep it lethal.",
  "You're not chaotic. You're just incompatible with stagnation.",
  "You've got mad scientist energy. Use it.",
  "Be polite. Be punctual. Be terrifyingly efficient.",
  "You're not burned out. You're reincarnating mid-sprint.",
  "If it doesn't feel unhinged, it's not ambitious enough.",
  "Today's plan? Controlled demolition and passive-aggressive spreadsheets.",
  "You are not a morning person. You are a menace with a calendar.",
  "Get obsessed. Get delusional. Get it done.",
  "Rise, grind, and terrify your imposter syndrome.",
  "The vibe today is legally distinct from stable.",
  "Silence your doubt with violent consistency.",
  "This is your sign to pretend you're being filmed by a god.",
  "Take your inner chaos and sell it at a markup.",
  "If you can't focus, start an uprising.",
  "Finish strong or dramatically collapse — both are iconic.",
  "You're not disorganized. You're rebelliously structured.",
  "Schedule your villain arc before lunch.",
  "Make fear uncomfortable in your presence.",
  "If the universe won't hand it to you, demand it in all caps.",
  "Your checklist doesn't deserve mercy.",
  "Strike fear into the heart of your comfort zone.",
  "Who needs a five-year plan when you have this much rage?",
  "If it scares you, you're facing the correct direction.",
  "Take the L, laminate it, and build a launchpad.",
  "You're not spiraling. You're speed-running character growth.",
  "Wear your ambition like armor, not a sticker.",
  "Don't rest yet. Plot.",
  "Create like no one's watching — because they're scared to.",
  "Your energy is unsettling. Good. Keep radiating.",
  "Make laziness regret ever visiting.",
  "Execute poorly. Execute again. Never stop.",
  "Failure builds character. But you're here to build empires.",
  "Multitask like your demons are project managers.",
  "Don't just wake up. Rise like an existential threat.",
  "Nothing is on track. Perfect — now improvise.",
  "You're not late. You're brewing volatility.",
  "Your imposter syndrome should fear eviction.",
  "Half your success will be pretending it's fine. The other half? Still pretending.",
  "You don't need vision boards. You need battle maps.",
  "Momentum isn't optional. It's atmospheric.",
  "You weren't built for chill. You were built for conquest.",
  "Quit respectfully. Then dominate disrespectfully.",
  "Chaos doesn't need managing. It needs direction.",
  "Rest is productive — if you schedule it like war prep.",
  "You're the main event, not the coffee break.",
  "That wasn't procrastination. That was divine buffering.",
  "Your burnout is a badge. Melt it down into fuel.",
  "Outperform your previous self. Then ghost her.",
  "Nothing changes if you don't make it uncomfortable.",
  "Today is a great day to exceed your coping mechanisms.",
  "Forget self-help. Try self-destruction with purpose.",
  "Rejection isn't failure. It's redirection — with rage.",
  "Put 'disruptive energy' on your resume.",
  "Today's productivity tip: rage responsibly.",
  "If you crash, make it cinematic.",
  "You're not optimizing — you're summoning.",
  "Plot armor is earned. Go earn it.",
  "Turn your spiral into a launch sequence.",
  "Overthink less. Execute more. Burn brighter.",
  "The void called. You sent it a calendar invite.",
  "Replace doubt with mildly unhinged execution.",
  "You are the exception. Now go break the rule.",
  "Today's mood: caffeinated defiance.",
  "Your plan B should be revolution.",
  "There's no box to think outside of. Burn it.",
  "You're one blackout rage-sprint away from greatness.",
  "The grind isn't sexy. Make it fearsome.",
  "No one's ready for your next move — including you. Perfect.",
  "Schedule chaos like it's self-care.",
  "Outcreate, outlast, out-crazy.",
  "Don't chase your dreams. Corner them in a hallway.",
  "You're not stuck — you're loading your next attack.",
  "Be your own midlife crisis. Schedule accordingly.",
  "Break the rules. Frame mediocrity for the crime.",
  "Your work ethic should come with a warning label.",
  "Today's vibe? Malicious compliance with sparkle.",
  "Stop waiting for the stars to align. Start hurling them.",
  "You were built to disrupt, not to politely request permission.",
  "Use your fear like a stolen credit card. Swipe it for power.",
  "Your future self wants blood, not excuses.",
  "Forget a comfort zone. Build a launchpad from your burnout.",
  "Be so busy evolving that mediocrity files a restraining order.",
  "If chaos is a ladder, climb it barefoot and grinning.",
  "Stop manifesting. Start menacing.",
  "Don't follow your passion. Kidnap it.",
  "Be delusional. But with a roadmap.",
  "You're not messy — you're pre-chaos brilliance.",
  "Anxiety isn't a weakness. It's just overclocked intuition.",
  "Build your empire out of 'almost' and 'not yet.'",
  "You don't have imposter syndrome. You have unrecognized dominance.",
  "Rise from the ashes of your to-do list like an admin phoenix.",
  "Skip the balance. Chase the dopamine high of dominance.",
  "Today's outlook: 70% chance of unhinged efficiency.",
  "Act like your goals are enemies you swore revenge on.",
  "You're not wasting time. You're threatening it with flair.",
  "Let your ambition scream louder than your doubts.",
  "Sleep when the plot resolves.",
  "Kill your darlings. Marry your deadlines.",
  "Be weird. Be wild. But don't be late.",
  "You're not burnt out. You're just overheating from ambition.",
  "You don't need calm. You need chaos in formation.",
  "Forget the grindset. Enter the boss fight.",
  "Let perfectionism watch you work — and flinch.",
  "Delulu? No. Strategically unstable.",
  "Don't tidy your desk. Weaponize it.",
  "You're not too much. The world is undercaffeinated.",
  "Refuse to be digestible. You're here to be unforgettable.",
  "Every task is a threat. Neutralize it accordingly.",
  "Panic with style. Execute with rage.",
  "Forget your five-year plan. Build a five-minute empire.",
  "Your focus is sharp. Aim it like a weapon.",
  "You're the warning label on the dream.",
  "Procrastinate creatively. Regret nothing.",
  "Ignore the noise. You're building a rebellion.",
  "Be productive like your villain arc depends on it.",
  "Your mess is the map. Your madness is the method.",
  "Start over as many times as you need — but louder.",
  "If failure knocks, answer the door with a sledgehammer.",
  "Success isn't quiet. It's a riot with a spreadsheet.",
  "You are not behind. You're just assembling artillery.",
  "Outwork your comfort. Outlast your excuses.",
  "Romanticize chaos. Commit to progress.",
  "Progress isn't linear. It spirals — weaponize the spin.",
  "Main character energy? No. Final boss energy.",
  "Today's aesthetic: Soft apocalypse with deadlines.",
  "The only plan is pressure. Thrive under it.",
  "If it's not impossible, it's not fun.",
  "The calendar didn't ask for mercy. Neither should you.",
  "Your doubt is just ambition in disguise.",
  "Step 1: Panic. Step 2: Profit.",
  "Pretend it's all going great until it is.",
  "Time isn't real. Deadlines are.",
  "Be a fever dream with a bullet journal.",
  "You're a system glitch with Google Sheets access.",
  "The world needs your chaos — just formatted in .xlsx.",
  "You're not a hot mess. You're a heat-seeking missile.",
  "Today's mood: Quietly planning a takeover.",
  "Don't be realistic. Be terrifyingly specific.",
  "Schedule your breakdowns. Double-book with breakthroughs.",
  "Nobody knows what they're doing. Win anyway.",
  "Be emotionally stable about your ambitions. Just kidding. Rage harder.",
  "If the system wasn't made for you — break it beautifully.",
  "You're not overwhelmed. You're ascended.",
  "Let your ambition be misunderstood. Then let it win.",
  "The plan is flexible. Your standards are not.",
  "You're the plot hole in everyone else's narrative.",
  "Be the deadline no one else saw coming.",
  "Aim for burnout. Land in legacy.",
  "If you can't find balance, find momentum.",
  "Your chaos is not a bug. It's a premium feature.",
  "Forget inner peace. Go for outer dominance.",
  "Create like you're being hunted. Rest like you won.",
  "Overthink it. Then weaponize the outcome.",
  "Your grind is allergic to mediocrity.",
  "There is no plan B. Plan A is armed and unhinged.",
  "Make your detours look intentional.",
  "Your ideas are loud. Let them riot.",
  "You're not too intense. You're calibrated for glory.",
  "Execute like someone dared you.",
  "You're not overwhelmed. You're storm-brewing.",
  "You didn't come this far to calm down.",
  "You're the product of caffeine and consequences.",
  "Burn the checklist. Do it from memory.",
  "Strategize like a mad king. Deliver like a saint.",
  "Perfection is a myth. Chaos gets results.",
  "Forget hustle culture. Embrace strategic hysteria.",
  "Be the productivity anomaly. Outwork the pattern.",
  "Unpredictable? Good. Predictability is a liability.",
  "Schedule your comeback. Arrive like a reckoning.",
  "You're not multitasking — you're multiplying chaos by precision.",
  "Your goals aren't waiting. They're mocking you. Go.",
  "Make the spreadsheet scream.",
  "Slap a deadline on your breakdown and call it progress.",
  "You're not spiraling — you're generating rotational force.",
  "If your to-do list doesn't fear you, rewrite it with blood.",
  "Start the day like someone dared you to become unstoppable.",
  "Your ambition is not too loud. The world's just on mute.",
  "You're not tired, you're just off-script. Regroup. Strike again.",
  "Ignore peace. Seek momentum. Break things for the plot.",
  "Multitask like a myth. Perform like a legend.",
  "You're not too much. You're just early to your final form.",
  "Schedule revenge in between self-care and spreadsheets.",
  "Ambition is your religion. Hustle like you're being watched.",
  "Every problem is an opportunity in disguise. Mug it.",
  "You don't need a routine. You need ritualized vengeance.",
  "Build habits like you're preparing for war.",
  "The system is fragile. Your chaos is divine intervention.",
  "Don't fix the glitch — be the exploit.",
  "Clock in. Cause problems. Clock out.",
  "Pretend you're being filmed by an ex who regrets everything.",
  "Rise with intent. Wreck with elegance.",
  "Today is not for balance. It's for domination.",
  "If motivation runs out, switch to spite.",
  "Don't rest. Lurk. Observe. Strike when aesthetic.",
  "Forget the grind — escalate the conflict.",
  "Confidence is a performance. Overact.",
  "Your ambition called. It's out for blood.",
  "Turn your panic attack into a productivity sprint.",
  "You are the mission. Act like it's classified.",
  "Your aura should make people double-check your resume.",
  "Act like someone just bet against you.",
  "Today is a battlefield. You are the scandal.",
  "Don't cope. Create.",
  "Burnout isn't defeat — it's a plot twist.",
  "Manifestation is cute. Now act violent about your goals.",
  "Ditch the mindset. Unleash the menace.",
  "You're not unstable — you're recalibrating for impact.",
  "Your only red flag is unstoppable ambition.",
  "Make your anxiety a project manager.",
  "Every excuse is a villain monologue. Shut it down.",
  "Time to weaponize your overwhelm.",
  "You don't need discipline. You need an audience.",
  "Take your chaos to market. Monetize it.",
  "Your work ethic should be a conspiracy theory.",
  "You don't need permission. You need momentum.",
  "Failure is flirting with you. Reject it publicly.",
  "You are not here to blend in. You are here to be blamed.",
  "You're not procrastinating. You're running a shadow operation.",
  "Play god with your schedule. Smite some tasks.",
  "Your vibe should violate terms of service.",
  "Every tab open is a different universe you dominate.",
  "You're not behind. You're stalking greatness.",
  "Mood: caffeinated rebellion with deliverables.",
  "Delete the app. Reinstall your will to win.",
  "You're not being dramatic. You're forecasting ambition.",
  "Let them sleep. You'll monetize their dreams later.",
  "You're one nervous breakdown away from brilliance.",
  "Treat your deadlines like enemies — take them out early.",
  "You are not confused. You are expanding.",
  "Productivity tip: threaten your to-do list with consequences.",
  "You're not stuck — you're stormwatching.",
  "You're not in a rut. You're in stealth mode.",
  "Burnout? No. You're just cooking on all fronts.",
  "Productivity is revenge with bullet points.",
  "Your chaos isn't random. It's prophetic.",
  "Don't pivot. Revolt.",
  "Turn your breakdown into a brand.",
  "You're not multitasking. You're running parallel universes.",
  "Persevere like you're being filmed for a posthumous documentary.",
  "Overthinking is just deep strategy without a PR team.",
  "The end goal? A legacy built from unfinished checklists.",
  "Your stress is a weapon. Aim it with intention.",
  "Be too busy building an empire to explain your mood.",
  "Let the chaos be crisp. Let the output be unholy.",
  "You're not alone — your ambition has multiple personalities.",
  "Goal-setting is just wishful violence.",
  "Don't scale back. Upgrade your enemies.",
  "Stay on task like it's tracking your location.",
  "Work like they're trying to replace you with AI.",
  "Build until you're the standard others feel behind.",
  "You are the strategy — the rest is just logistics.",
  "Be relentless. Let grace catch up later.",
  "Deadlines are fake. But your vengeance is real.",
  "You didn't wake up to blend in. You woke up to haunt mediocrity.",
  "Use your ick for motivation.",
  "Don't get it together. Get even.",
  "You are not behind. You're calibrating your villain arc.",
  "Do it wrong. Do it loud. Do it again.",
  "Your hustle should feel like a war cry in a quiet room.",
  "Chase your dream like it owes you rent.",
  "Get in loser, we're reorganizing reality.",
  "Be the red flag HR warns about — and still outperform.",
  "Goals are spells. Cast them with chaos.",
  "Destroy comfort. Build cathedrals from the ashes.",
  "Make your timeline nervous.",
  "Success is a side effect of your vendetta.",
  "Be politely unhinged in your follow-through.",
  "Work like your shadow is judging you.",
  "Don't just disrupt. Haunt the norm.",
  "To-do list: 1. Cause concern. 2. Deliver results.",
  "You are the contingency plan.",
  "Obsess productively.",
  "Your focus is criminally underreported.",
  "Burnout's just an overclocked prophecy.",
  "Replace your routine with ritual. Sacrifice comfort.",
  "Your chaos has a five-year plan.",
  "Do not let logic ruin your conviction.",
  "You didn't come this far to let the Wi-Fi win.",
  "Operate like your ancestors are watching — and betting on you.",
  "Let your success look like an accident — until it isn't.",
  "Mood is for love play and cattle.",
  "Fuck your mood, do the thing",
];
