const List<String> motivationalQuotes = [
  "Discipline is hot, mediocrity is boring. Become ungovernable.",
  "Discipline is hot, mediocrity is boring. Get dramatic with your ambition.",
  "Discipline is hot, mediocrity is boring. Pretend you're in a montage.",
  "Discipline is hot, mediocrity is boring. Today owes you nothing. Take it anyway.",
  "Be the glitch in the matrix.",
  "Discipline is hot now — and that's a you problem. Become someone your ex fears.",
  "Discipline is hot now — and that's a you problem. Conquer something today.",
  "Do it for the plot.",
  "It's a Tuesday, not a crisis. Pretend you're in a montage.",
  "Silence the inner hater. Become ungovernable.",
  "Silence the inner hater. Unleash main character energy.",
  "That's just the Wi-Fi talking. Today owes you nothing.",
  "Get dramatic with your ambition.",
  "Unleash main character energy.",
  "It's your comfort zone whispering.",
  "It's your comfort zone whispering. Get mad, then get moving.",
  "It's your dopamine addiction. Be the glitch in the matrix.",
  "It's your dopamine addiction. Become ungovernable.",
  "It's your fear of failure. Become ungovernable.",
  "It's your fear of failure. Unleash main character energy.",
  "Silence the inner hater. Be the glitch in the matrix.",
  "Silence the inner hater. Get mad.",
  "Silence the inner hater. Unleash main character energy.",
  "Nobody is coming to save you — and mediocrity is boring.",
  "Become ungovernable.",
  "Nobody is coming to save you — and that's a you problem.",
  "Nobody is coming to save you — Unleash main character energy.",
  "Nobody is coming to save you — Be the glitch in the matrix.",
  "Nobody is coming to save you.",
  "Nobody is coming to save you — Conquer something today.",
  "It's a Tuesday, not a crisis. Become someone your ex fears.",
  "It's a Tuesday, not a crisis. Do it for the plot.",
  "Nobody is coming to save you — it's just inertia. Be the glitch in the matrix.",
  "Nobody is coming to save you — it's just inertia. Become someone your ex fears.",
  "It's just inertia. Become ungovernable.",
  "It's your comfort zone whispering. Become ungovernable.",
  "It's your dopamine addiction.",
  "Today owes you nothing.",

  "Romanticize your struggle — and mediocrity is boring. Become ungovernable.",
  "Romanticize your struggle — and mediocrity is boring. Conquer something today.",
  "Romanticize your struggle — and mediocrity is boring. Get dramatic with your ambition.",
  "Romanticize your struggle — and mediocrity is boring. Get mad, then get moving.",
  "Romanticize your struggle — and that's a you problem. Be the glitch in the matrix.",
  "Romanticize your struggle — and that's a you problem. Become someone your ex fears.",
  "Romanticize your struggle — and that's a you problem. Become ungovernable.",
  "Romanticize your struggle — and that's a you problem. Get dramatic with your ambition.",
  "Romanticize your struggle — and that's a you problem. Today owes you nothing. Take it anyway.",
  "Romanticize your struggle — and that's a you problem. Unleash main character energy.",
  "Romanticize your struggle — it's your avoidance strategy. Be the glitch in the matrix.",
  "Romanticize your struggle — it's your avoidance strategy. Become ungovernable.",
  "Romanticize your struggle — it's your avoidance strategy. Conquer something today.",
  "Romanticize your struggle — it's your avoidance strategy. Today owes you nothing. Take it anyway.",
  "Romanticize your struggle — it's a Tuesday, not a crisis. Be the glitch in the matrix.",
  "Romanticize your struggle — it's a Tuesday, not a crisis. Become someone your ex fears.",
  "Romanticize your struggle — it's a Tuesday, not a crisis. Do it for the plot.",
  "Romanticize your struggle — it's a Tuesday, not a crisis. Unleash main character energy.",
  "Romanticize your struggle — it's just inertia. Become someone your ex fears.",
  "Romanticize your struggle — it's just inertia. Conquer something today.",
  "Romanticize your struggle — it's just inertia. Get mad, then get moving.",
  "Romanticize your struggle — it's just inertia. Pretend you're in a montage.",
  "Romanticize your struggle — it's just inertia. Today owes you nothing. Take it anyway.",
  "Romanticize your struggle — it's your comfort zone whispering. Become ungovernable.",
  "Romanticize your struggle — it's your comfort zone whispering. Unleash main character energy.",
  "Romanticize your struggle — it's your dopamine addiction. Be the glitch in the matrix.",
  "Romanticize your struggle — it's your dopamine addiction. Get dramatic with your ambition.",
  "Romanticize your struggle — it's your dopamine addiction. Get mad, then get moving.",
  "Romanticize your struggle — it's your dopamine addiction. Unleash main character energy.",
  "Romanticize your struggle — it's your fear of failure. Get mad, then get moving.",
  "Romanticize your struggle — it's your fear of failure. Pretend you're in a montage.",
  "Romanticize your struggle — silence the inner hater. Do it for the plot.",
  "Romanticize your struggle — silence the inner hater. Today owes you nothing. Take it anyway.",
  "Romanticize your struggle — that's just the Wi-Fi talking. Do it for the plot.",
  "Romanticize your struggle — that's just the Wi-Fi talking. Get mad, then get moving.",
  "Romanticize your struggle — that's just the Wi-Fi talking. Today owes you nothing. Take it anyway.",
  "Romanticize your struggle — that's just the Wi-Fi talking. Unleash main character energy.",
  "Self-care isn't just candles — and mediocrity is boring. Become someone your ex fears.",
  "Self-care isn't just candles — and mediocrity is boring. Get dramatic with your ambition.",
  "Self-care isn't just candles — and mediocrity is boring. Pretend you're in a montage.",
  "Self-care isn't just candles — and mediocrity is boring. Today owes you nothing. Take it anyway.",
  "Self-care isn't just candles — and mediocrity is boring. Unleash main character energy.",
  "Self-care isn't just candles — and that's a you problem. Be the glitch in the matrix.",
  "Self-care isn't just candles — and that's a you problem. Conquer something today.",
  "Self-care isn't just candles — it's your avoidance strategy. Get dramatic with your ambition.",
  "Self-care isn't just candles — it's your avoidance strategy. Get mad, then get moving.",
  "Self-care isn't just candles — it's a Tuesday, not a crisis. Become ungovernable.",
  "Self-care isn't just candles — it's a Tuesday, not a crisis. Get dramatic with your ambition.",
  "Self-care isn't just candles — it's a Tuesday, not a crisis. Unleash main character energy.",
  "Self-care isn't just candles — it's your comfort zone whispering. Be the glitch in the matrix.",
  "Self-care isn't just candles — it's your comfort zone whispering. Do it for the plot.",
  "Self-care isn't just candles — it's your comfort zone whispering. Get mad, then get moving.",
  "Self-care isn't just candles — it's your dopamine addiction. Become someone your ex fears.",
  "Self-care isn't just candles — it's your dopamine addiction. Get mad, then get moving.",
  "Self-care isn't just candles — it's your dopamine addiction. Pretend you're in a montage.",
  "Self-care isn't just candles — it's your dopamine addiction. Today owes you nothing. Take it anyway.",
  "Self-care isn't just candles — it's your fear of failure. Be the glitch in the matrix.",
  "Self-care isn't just candles — it's your fear of failure. Do it for the plot.",
  "Self-care isn't just candles — it's your fear of failure. Unleash main character energy.",
  "Self-care isn't just candles — silence the inner hater. Be the glitch in the matrix.",
  "Self-care isn't just candles — silence the inner hater. Become ungovernable.",
  "Self-care isn't just candles — silence the inner hater. Conquer something today.",
  "Self-care isn't just candles — silence the inner hater. Today owes you nothing. Take it anyway.",
  "Self-care isn't just candles — that's just the Wi-Fi talking. Conquer something today.",
  "Self-care isn't just candles — that's just the Wi-Fi talking. Get dramatic with your ambition.",
  "Self-care isn't just candles — that's just the Wi-Fi talking. Unleash main character energy.",
  "Success isn't waiting — and mediocrity is boring. Be the glitch in the matrix.",
  "Success isn't waiting — and mediocrity is boring. Become ungovernable.",
  "Success isn't waiting — and mediocrity is boring. Do it for the plot.",
  "Success isn't waiting — and mediocrity is boring. Get dramatic with your ambition.",
  "Success isn't waiting — and mediocrity is boring. Today owes you nothing. Take it anyway.",
  "Success isn't waiting — and mediocrity is boring. Unleash main character energy.",
  "Success isn't waiting — and that's a you problem. Be the glitch in the matrix.",
  "Success isn't waiting — and that's a you problem. Do it for the plot.",
  "Success isn't waiting — it's your avoidance strategy. Become someone your ex fears.",
  "Success isn't waiting — it's your avoidance strategy. Become ungovernable.",
  "Success isn't waiting — it's your avoidance strategy. Conquer something today.",
  "Success isn't waiting — it's your avoidance strategy. Do it for the plot.",
  "Success isn't waiting — it's your avoidance strategy. Today owes you nothing. Take it anyway.",
  "Success isn't waiting — it's your avoidance strategy. Unleash main character energy.",
  "Success isn't waiting — it's a Tuesday, not a crisis. Become someone your ex fears.",
  "Success isn't waiting — it's a Tuesday, not a crisis. Get mad, then get moving.",
  "Success isn't waiting — it's a Tuesday, not a crisis. Pretend you're in a montage.",
  "Success isn't waiting — it's just inertia. Get dramatic with your ambition.",
  "Success isn't waiting — it's just inertia. Pretend you're in a montage.",
  "Success isn't waiting — it's your comfort zone whispering. Become ungovernable.",
  "Success isn't waiting — it's your comfort zone whispering. Get dramatic with your ambition.",
  "Success isn't waiting — it's your comfort zone whispering. Get mad, then get moving.",
  "Success isn't waiting — it's your comfort zone whispering. Today owes you nothing. Take it anyway.",
  "Success isn't waiting — it's your dopamine addiction. Become someone your ex fears.",
  "Success isn't waiting — it's your dopamine addiction. Get dramatic with your ambition.",
  "Success isn't waiting — it's your dopamine addiction. Unleash main character energy.",
  "Success isn't waiting — it's your fear of failure. Get dramatic with your ambition.",
  "Success isn't waiting — it's your fear of failure. Today owes you nothing. Take it anyway.",
  "Success isn't waiting — silence the inner hater. Become someone your ex fears.",
  "Success isn't waiting — silence the inner hater. Conquer something today.",
  "Success isn't waiting — that's just the Wi-Fi talking. Do it for the plot.",
  "Success isn't waiting — that's just the Wi-Fi talking. Get dramatic with your ambition.",
  "Success isn't waiting — that's just the Wi-Fi talking. Pretend you're in a montage.",
  "The universe isn't against you — and mediocrity is boring. Be the glitch in the matrix.",
  "The universe isn't against you — and mediocrity is boring. Become ungovernable.",
  "The universe isn't against you — and mediocrity is boring. Get dramatic with your ambition.",
  "The universe isn't against you — and mediocrity is boring. Get mad, then get moving.",
  "The universe isn't against you — and mediocrity is boring. Today owes you nothing. Take it anyway.",
  "The universe isn't against you — and mediocrity is boring. Unleash main character energy.",
  "The universe isn't against you — and that's a you problem. Be the glitch in the matrix.",
  "The universe isn't against you — and that's a you problem. Pretend you're in a montage.",
  "The universe isn't against you — it's your avoidance strategy. Become ungovernable.",
  "The universe isn't against you — it's your avoidance strategy. Do it for the plot.",
  "The universe isn't against you — it's your avoidance strategy. Pretend you're in a montage.",
  "The universe isn't against you — it's your avoidance strategy. Unleash main character energy.",
  "The universe isn't against you — it's a Tuesday, not a crisis. Become someone your ex fears.",
  "The universe isn't against you — it's a Tuesday, not a crisis. Do it for the plot.",
  "The universe isn't against you — it's a Tuesday, not a crisis. Get dramatic with your ambition.",
  "The universe isn't against you — it's a Tuesday, not a crisis. Get mad, then get moving.",
  "The universe isn't against you — it's a Tuesday, not a crisis. Pretend you're in a montage.",
  "The universe isn't against you — it's just inertia. Conquer something today.",
  "The universe isn't against you — it's just inertia. Do it for the plot.",
  "The universe isn't against you — it's just inertia. Get mad, then get moving.",
  "The universe isn't against you — it's your comfort zone whispering. Today owes you nothing. Take it anyway.",
  "The universe isn't against you — it's your dopamine addiction. Become someone your ex fears.",
  "The universe isn't against you — it's your dopamine addiction. Become ungovernable.",
  "The universe isn't against you — it's your dopamine addiction. Pretend you're in a montage.",
  "The universe isn't against you — it's your fear of failure. Become ungovernable.",
  "The universe isn't against you — it's your fear of failure. Conquer something today.",
  "The universe isn't against you — silence the inner hater. Conquer something today.",
  "The universe isn't against you — silence the inner hater. Get mad, then get moving.",
  "The universe isn't against you — that's just the Wi-Fi talking. Become ungovernable.",
  "The universe isn't against you — that's just the Wi-Fi talking. Pretend you're in a montage.",
  "You are not lazy — and mediocrity is boring. Be the glitch in the matrix.",
  "You are not lazy — and mediocrity is boring. Become ungovernable.",
  "You are not lazy — and mediocrity is boring. Get dramatic with your ambition.",
  "You are not lazy — and mediocrity is boring. Pretend you're in a montage.",
  "You are not lazy — and mediocrity is boring. Today owes you nothing. Take it anyway.",
  "You are not lazy — and that's a you problem. Become someone your ex fears.",
  "You are not lazy — and that's a you problem. Become ungovernable.",
  "You are not lazy — and that's a you problem. Conquer something today.",
  "You are not lazy — and that's a you problem. Get mad, then get moving.",
  "You are not lazy — it's your avoidance strategy. Conquer something today.",
  "You are not lazy — it's your avoidance strategy. Get dramatic with your ambition.",
  "You are not lazy — it's your avoidance strategy. Pretend you're in a montage.",
  "You are not lazy — it's your avoidance strategy. Today owes you nothing. Take it anyway.",
  "You are not lazy — it's a Tuesday, not a crisis. Do it for the plot.",
  "You are not lazy — it's a Tuesday, not a crisis. Get dramatic with your ambition.",
  "You are not lazy — it's a Tuesday, not a crisis. Today owes you nothing. Take it anyway.",
  "You are not lazy — it's just inertia. Become someone your ex fears.",
  "You are not lazy — it's just inertia. Get dramatic with your ambition.",
  "You are not lazy — it's just inertia. Today owes you nothing. Take it anyway.",
  "You are not lazy — it's just inertia. Unleash main character energy.",
  "You are not lazy — it's your comfort zone whispering. Be the glitch in the matrix.",
  "You are not lazy — it's your comfort zone whispering. Get mad, then get moving.",
  "You are not lazy — it's your comfort zone whispering. Pretend you're in a montage.",
  "You are not lazy — it's your dopamine addiction. Be the glitch in the matrix.",
  "You are not lazy — it's your dopamine addiction. Become ungovernable.",
  "You are not lazy — it's your dopamine addiction. Pretend you're in a montage.",
  "You are not lazy — it's your fear of failure. Become someone your ex fears.",
  "You are not lazy — it's your fear of failure. Pretend you're in a montage.",
  "You are not lazy — silence the inner hater. Become ungovernable.",
  "You are not lazy — silence the inner hater. Do it for the plot.",
  "You are not lazy — silence the inner hater. Today owes you nothing. Take it anyway.",
  "You are not lazy — silence the inner hater. Unleash main character energy.",
  "You are not lazy — that's just the Wi-Fi talking. Do it for the plot.",
  "You are not lazy — that's just the Wi-Fi talking. Get dramatic with your ambition.",
  "You are not lazy — that's just the Wi-Fi talking. Get mad, then get moving.",
  "You are not lazy — that's just the Wi-Fi talking. Today owes you nothing. Take it anyway.",
  "You are not lazy — that's just the Wi-Fi talking. Unleash main character energy.",
  "You are the plot twist — and mediocrity is boring. Be the glitch in the matrix.",
  "You are the plot twist — and that's a you problem. Be the glitch in the matrix.",
  "You are the plot twist — and that's a you problem. Pretend you're in a montage.",
  "You are the plot twist — it's your avoidance strategy. Be the glitch in the matrix.",
  "You are the plot twist — it's your avoidance strategy. Become someone your ex fears.",
  "You are the plot twist — it's your avoidance strategy. Do it for the plot.",
  "You are the plot twist — it's your avoidance strategy. Get dramatic with your ambition.",
  "You are the plot twist — it's your avoidance strategy. Pretend you're in a montage.",
  "You are the plot twist — it's your avoidance strategy. Today owes you nothing. Take it anyway.",
  "You are the plot twist — it's a Tuesday, not a crisis. Become someone your ex fears.",
  "You are the plot twist — it's a Tuesday, not a crisis. Conquer something today.",
  "You are the plot twist — it's a Tuesday, not a crisis. Do it for the plot.",
  "You are the plot twist — it's a Tuesday, not a crisis. Get dramatic with your ambition.",
  "You are the plot twist — it's a Tuesday, not a crisis. Get mad, then get moving.",
  "You are the plot twist — it's just inertia. Conquer something today.",
  "You are the plot twist — it's just inertia. Get dramatic with your ambition.",
  "You are the plot twist — it's just inertia. Get mad, then get moving.",
  "You are the plot twist — it's just inertia. Today owes you nothing. Take it anyway.",
  "You are the plot twist — it's just inertia. Unleash main character energy.",
  "You are the plot twist — it's your comfort zone whispering. Be the glitch in the matrix.",
  "You are the plot twist — it's your comfort zone whispering. Become someone your ex fears.",
  "You are the plot twist — it's your comfort zone whispering. Conquer something today.",
  "You are the plot twist — it's your comfort zone whispering. Get dramatic with your ambition.",
  "You are the plot twist — it's your comfort zone whispering. Get mad, then get moving.",
  "You are the plot twist — it's your comfort zone whispering. Today owes you nothing. Take it anyway.",
  "You are the plot twist — it's your dopamine addiction. Become someone your ex fears.",
  "You are the plot twist — it's your dopamine addiction. Become ungovernable.",
  "You are the plot twist — it's your fear of failure. Become someone your ex fears.",
  "You are the plot twist — it's your fear of failure. Conquer something today.",
  "You are the plot twist — it's your fear of failure. Get mad, then get moving.",
  "You are the plot twist — it's your fear of failure. Unleash main character energy.",
  "You are the plot twist — silence the inner hater. Become ungovernable.",
  "You are the plot twist — silence the inner hater. Get dramatic with your ambition.",
  "You are the plot twist — silence the inner hater. Pretend you're in a montage.",
  "You are the plot twist — silence the inner hater. Today owes you nothing. Take it anyway.",
  "You are the plot twist — that's just the Wi-Fi talking. Pretend you're in a montage.",
  "You didn't come this far to nap — and mediocrity is boring. Become someone your ex fears.",
  "You didn't come this far to nap — and mediocrity is boring. Conquer something today.",
  "You didn't come this far to nap — and mediocrity is boring. Do it for the plot.",
  "You didn't come this far to nap — and mediocrity is boring. Today owes you nothing. Take it anyway.",
  "You didn't come this far to nap — and mediocrity is boring. Unleash main character energy.",
  "You didn't come this far to nap — and that's a you problem. Get dramatic with your ambition.",
  "You didn't come this far to nap — and that's a you problem. Today owes you nothing. Take it anyway.",
  "You didn't come this far to nap — it's your avoidance strategy. Be the glitch in the matrix.",
  "You didn't come this far to nap — it's your avoidance strategy. Become ungovernable.",
  "You didn't come this far to nap — it's your avoidance strategy. Conquer something today.",
  "You didn't come this far to nap — it's your avoidance strategy. Get dramatic with your ambition.",
  "You didn't come this far to nap — it's your avoidance strategy. Today owes you nothing. Take it anyway.",
  "You didn't come this far to nap — it's a Tuesday, not a crisis. Become ungovernable.",
  "You didn't come this far to nap — it's a Tuesday, not a crisis. Get dramatic with your ambition.",
  "You didn't come this far to nap — it's a Tuesday, not a crisis. Get mad, then get moving.",
  "You didn't come this far to nap — it's a Tuesday, not a crisis. Pretend you're in a montage.",
  "You didn't come this far to nap — it's just inertia. Conquer something today.",
  "You didn't come this far to nap — it's just inertia. Get mad, then get moving.",
  "You didn't come this far to nap — it's your comfort zone whispering. Become someone your ex fears.",
  "You didn't come this far to nap — it's your comfort zone whispering. Do it for the plot.",
  "You didn't come this far to nap — it's your comfort zone whispering. Get dramatic with your ambition.",
  "You didn't come this far to nap — it's your comfort zone whispering. Unleash main character energy.",
  "You didn't come this far to nap — it's your dopamine addiction. Get dramatic with your ambition.",
  "You didn't come this far to nap — it's your dopamine addiction. Pretend you're in a montage.",
  "You didn't come this far to nap — it's your dopamine addiction. Today owes you nothing. Take it anyway.",
  "You didn't come this far to nap — it's your fear of failure. Do it for the plot.",
  "You didn't come this far to nap — it's your fear of failure. Get dramatic with your ambition.",
  "You didn't come this far to nap — silence the inner hater. Conquer something today.",
  "You didn't come this far to nap — silence the inner hater. Get dramatic with your ambition.",
  "You didn't come this far to nap — that's just the Wi-Fi talking. Get dramatic with your ambition.",
  "You didn't come this far to nap — that's just the Wi-Fi talking. Pretend you're in a montage.",
  "You don't lack time — and mediocrity is boring. Become ungovernable.",
  "You don't lack time — and mediocrity is boring. Do it for the plot.",
  "You don't lack time — and that's a you problem. Become someone your ex fears.",
  "You don't lack time — and that's a you problem. Become ungovernable.",
  "You don't lack time — and that's a you problem. Do it for the plot.",
  "You don't lack time — and that's a you problem. Pretend you're in a montage.",
  "You don't lack time — and that's a you problem. Today owes you nothing. Take it anyway.",
  "You don't lack time — and that's a you problem. Unleash main character energy.",
  "You don't lack time — it's a Tuesday, not a crisis. Be the glitch in the matrix.",
  "You don't lack time — it's a Tuesday, not a crisis. Become someone your ex fears.",
  "You don't lack time — it's a Tuesday, not a crisis. Become ungovernable.",
  "You don't lack time — it's a Tuesday, not a crisis. Do it for the plot.",
  "You don't lack time — it's a Tuesday, not a crisis. Get dramatic with your ambition.",
  "You don't lack time — it's a Tuesday, not a crisis. Today owes you nothing. Take it anyway.",
  "You don't lack time — it's just inertia. Become someone your ex fears.",
  "You don't lack time — it's just inertia. Unleash main character energy.",
  "You don't lack time — it's your comfort zone whispering. Be the glitch in the matrix.",
  "You don't lack time — it's your comfort zone whispering. Become someone your ex fears.",
  "You don't lack time — it's your comfort zone whispering. Become ungovernable.",
  "You don't lack time — it's your comfort zone whispering. Do it for the plot.",
  "You don't lack time — it's your comfort zone whispering. Today owes you nothing. Take it anyway.",
  "You don't lack time — it's your dopamine addiction. Be the glitch in the matrix.",
  "You don't lack time — it's your fear of failure. Conquer something today.",
  "You don't lack time — silence the inner hater. Get dramatic with your ambition.",
  "You don't lack time — silence the inner hater. Pretend you're in a montage.",
  "You don't lack time — silence the inner hater. Today owes you nothing. Take it anyway.",
  "You don't lack time — silence the inner hater. Unleash main character energy.",
  "You don't lack time — that's just the Wi-Fi talking. Be the glitch in the matrix.",
  "You don't lack time — that's just the Wi-Fi talking. Become ungovernable.",
  "You don't lack time — that's just the Wi-Fi talking. Get dramatic with your ambition.",
  "You don't lack time — that's just the Wi-Fi talking. Pretend you're in a montage.",
  "You don't lack time — that's just the Wi-Fi talking. Unleash main character energy.",
  "You're not tired — and mediocrity is boring. Be the glitch in the matrix.",
  "You're not tired — and mediocrity is boring. Become someone your ex fears.",
  "You're not tired — and mediocrity is boring. Do it for the plot.",
  "You're not tired — and that's a you problem. Conquer something today.",
  "You're not tired — and that's a you problem. Do it for the plot.",
  "You're not tired — and that's a you problem. Get dramatic with your ambition.",
  "You're not tired — and that's a you problem. Pretend you're in a montage.",
  "You're not tired — it's your avoidance strategy. Become someone your ex fears.",
  "You're not tired — it's your avoidance strategy. Do it for the plot.",
  "You're not tired — it's your avoidance strategy. Today owes you nothing. Take it anyway.",
  "You're not tired — it's a Tuesday, not a crisis. Be the glitch in the matrix.",
  "You're not tired — it's a Tuesday, not a crisis. Become someone your ex fears.",
  "You're not tired — it's a Tuesday, not a crisis. Conquer something today.",
  "You're not tired — it's a Tuesday, not a crisis. Get mad, then get moving.",
  "You're not tired — it's a Tuesday, not a crisis. Today owes you nothing. Take it anyway.",
  "You're not tired — it's a Tuesday, not a crisis. Unleash main character energy.",
  "You're not tired — it's just inertia. Become someone your ex fears.",
  "You're not tired — it's just inertia. Become ungovernable.",
  "You're not tired — it's just inertia. Conquer something today.",
  "You're not tired — it's just inertia. Get dramatic with your ambition.",
  "You're not tired — it's just inertia. Today owes you nothing. Take it anyway.",
  "You're not tired — it's just inertia. Unleash main character energy.",
  "You're not tired — it's your comfort zone whispering. Get dramatic with your ambition.",
  "You're not tired — it's your comfort zone whispering. Today owes you nothing. Take it anyway.",
  "You're not tired — it's your dopamine addiction. Become ungovernable.",
  "You're not tired — it's your dopamine addiction. Conquer something today.",
  "You're not tired — it's your dopamine addiction. Do it for the plot.",
  "You're not tired — it's your dopamine addiction. Today owes you nothing. Take it anyway.",
  "You're not tired — it's your dopamine addiction. Unleash main character energy.",
  "You're not tired — it's your fear of failure. Conquer something today.",
  "You're not tired — it's your fear of failure. Do it for the plot.",
  "You're not tired — it's your fear of failure. Get mad, then get moving.",
  "You're not tired — it's your fear of failure. Pretend you're in a montage.",
  "You're not tired — it's your fear of failure. Today owes you nothing. Take it anyway.",
  "You're not tired — silence the inner hater. Become someone your ex fears.",
  "You're not tired — silence the inner hater. Get dramatic with your ambition.",
  "You're not tired — silence the inner hater. Today owes you nothing. Take it anyway.",
  "You're not tired — that's just the Wi-Fi talking. Be the glitch in the matrix.",
  "You're not tired — that's just the Wi-Fi talking. Become someone your ex fears.",
  "You're not tired — that's just the Wi-Fi talking. Become ungovernable.",
  "You're not tired — that's just the Wi-Fi talking. Conquer something today.",
  "You're not tired — that's just the Wi-Fi talking. Get mad, then get moving.",
  "You're not tired — that's just the Wi-Fi talking. Today owes you nothing. Take it anyway.",
  "Your dream job isn't on LinkedIn — and mediocrity is boring. Conquer something today.",
  "Your dream job isn't on LinkedIn — and mediocrity is boring. Get dramatic with your ambition.",
  "Your dream job isn't on LinkedIn — and mediocrity is boring. Get mad, then get moving.",
  "Your dream job isn't on LinkedIn — and that's a you problem. Become someone your ex fears.",
  "Your dream job isn't on LinkedIn — and that's a you problem. Get mad, then get moving.",
  "Your dream job isn't on LinkedIn — and that's a you problem. Unleash main character energy.",
  "Your dream job isn't on LinkedIn — it's your avoidance strategy. Do it for the plot.",
  "Your dream job isn't on LinkedIn — it's a Tuesday, not a crisis. Conquer something today.",
  "Your dream job isn't on LinkedIn — it's a Tuesday, not a crisis. Unleash main character energy.",
  "Your dream job isn't on LinkedIn — it's just inertia. Become ungovernable.",
  "Your dream job isn't on LinkedIn — it's just inertia. Get dramatic with your ambition.",
  "Your dream job isn't on LinkedIn — it's your comfort zone whispering. Become someone your ex fears.",
  "Your dream job isn't on LinkedIn — it's your comfort zone whispering. Conquer something today.",
  "Your dream job isn't on LinkedIn — it's your comfort zone whispering. Pretend you're in a montage.",
  "Your dream job isn't on LinkedIn — it's your fear of failure. Become someone your ex fears.",
  "Your dream job isn't on LinkedIn — it's your fear of failure. Do it for the plot.",
  "Your dream job isn't on LinkedIn — it's your fear of failure. Pretend you're in a montage.",
  "Your dream job isn't on LinkedIn — it's your fear of failure. Today owes you nothing. Take it anyway.",
  "Your dream job isn't on LinkedIn — silence the inner hater. Conquer something today.",
  "Your dream job isn't on LinkedIn — silence the inner hater. Do it for the plot.",
  "Your dream job isn't on LinkedIn — silence the inner hater. Get mad, then get moving.",
  "Your dream job isn't on LinkedIn — silence the inner hater. Pretend you're in a montage.",
  "Your dream job isn't on LinkedIn — that's just the Wi-Fi talking. Be the glitch in the matrix.",
  "Your dream job isn't on LinkedIn — that's just the Wi-Fi talking. Become someone your ex fears.",
  "Your dream job isn't on LinkedIn — that's just the Wi-Fi talking. Conquer something today.",
  "Your dream job isn't on LinkedIn — that's just the Wi-Fi talking. Get dramatic with your ambition.",
  "You're not stuck — you're paused — and mediocrity is boring. Become someone your ex fears.",
  "You're not stuck — you're paused — and mediocrity is boring. Do it for the plot.",
  "You're not stuck — you're paused — and mediocrity is boring. Get mad, then get moving.",
  "You're not stuck — you're paused — and that's a you problem. Become ungovernable.",
  "You're not stuck — you're paused — and that's a you problem. Conquer something today.",
  "You're not stuck — you're paused — and that's a you problem. Get dramatic with your ambition.",
  "You're not stuck — you're paused — and that's a you problem. Pretend you're in a montage.",
  "You're not stuck — you're paused — and that's a you problem. Today owes you nothing. Take it anyway.",
  "You're not stuck — you're paused — it's your avoidance strategy. Conquer something today.",
  "You're not stuck — you're paused — it's your avoidance strategy. Get dramatic with your ambition.",
  "You're not stuck — you're paused — it's your avoidance strategy. Pretend you're in a montage.",
  "You're not stuck — you're paused — it's a Tuesday, not a crisis. Become ungovernable.",
  "You're not stuck — you're paused — it's a Tuesday, not a crisis. Pretend you're in a montage.",
  "You're not stuck — you're paused — it's just inertia. Become ungovernable.",
  "You're not stuck — you're paused — it's just inertia. Get mad, then get moving.",
  "You're not stuck — you're paused — it's just inertia. Today owes you nothing. Take it anyway.",
  "You're not stuck — you're paused — it's your comfort zone whispering. Do it for the plot.",
  "You're not stuck — you're paused — it's your dopamine addiction. Become someone your ex fears.",
  "You're not stuck — you're paused — it's your dopamine addiction. Conquer something today.",
  "You're not stuck — you're paused — it's your dopamine addiction. Do it for the plot.",
  "You're not stuck — you're paused — it's your dopamine addiction. Get mad, then get moving.",
  "You're not stuck — you're paused — it's your fear of failure. Become ungovernable.",
  "You're not stuck — you're paused — it's your fear of failure. Conquer something today.",
  "You're not stuck — you're paused — it's your fear of failure. Do it for the plot.",
  "You're not stuck — you're paused — silence the inner hater. Become someone your ex fears.",
  "You're not stuck — you're paused — silence the inner hater. Become ungovernable.",
  "You're not stuck — you're paused — silence the inner hater. Conquer something today.",
  "You're not stuck — you're paused — silence the inner hater. Get mad, then get moving.",
  "You're not stuck — you're paused — silence the inner hater. Pretend you're in a montage.",
  "You're not stuck — you're paused — silence the inner hater. Today owes you nothing. Take it anyway.",
  "You're not stuck — you're paused — that's just the Wi-Fi talking. Do it for the plot.",
  "You're not stuck — you're paused — that's just the Wi-Fi talking. Get dramatic with your ambition.",
  "You're not stuck — you're paused — that's just the Wi-Fi talking. Get mad, then get moving.",
  "You're not unlucky — and mediocrity is boring. Become someone your ex fears.",
  "You're not unlucky — and mediocrity is boring. Become ungovernable.",
  "You're not unlucky — and mediocrity is boring. Get mad, then get moving.",
  "You're not unlucky — and that's a you problem. Do it for the plot.",
  "You're not unlucky — and that's a you problem. Get dramatic with your ambition.",
  "You're not unlucky — and that's a you problem. Pretend you're in a montage.",
  "You're not unlucky — it's your avoidance strategy. Be the glitch in the matrix.",
  "You're not unlucky — it's your avoidance strategy. Do it for the plot.",
  "You're not unlucky — it's your avoidance strategy. Unleash main character energy.",
  "You're not unlucky — it's a Tuesday, not a crisis. Become someone your ex fears.",
  "You're not unlucky — it's a Tuesday, not a crisis. Get dramatic with your ambition.",
  "You're not unlucky — it's a Tuesday, not a crisis. Pretend you're in a montage.",
  "You're not unlucky — it's just inertia. Be the glitch in the matrix.",
  "You're not unlucky — it's just inertia. Do it for the plot.",
  "You're not unlucky — it's just inertia. Get mad, then get moving.",
  "You're not unlucky — it's just inertia. Pretend you're in a montage.",
  "You're not unlucky — it's your comfort zone whispering. Be the glitch in the matrix.",
  "You're not unlucky — it's your comfort zone whispering. Become ungovernable.",
  "You're not unlucky — it's your comfort zone whispering. Conquer something today.",
  "You're not unlucky — it's your comfort zone whispering. Do it for the plot.",
  "You're not unlucky — it's your comfort zone whispering. Get dramatic with your ambition.",
  "You're not unlucky — it's your comfort zone whispering. Pretend you're in a montage.",
  "You're not unlucky — it's your comfort zone whispering. Unleash main character energy.",
  "You're not unlucky — it's your dopamine addiction. Do it for the plot.",
  "You're not unlucky — it's your dopamine addiction. Unleash main character energy.",
  "You're not unlucky — it's your fear of failure. Be the glitch in the matrix.",
  "You're not unlucky — it's your fear of failure. Conquer something today.",
  "You're not unlucky — it's your fear of failure. Pretend you're in a montage.",
  "You're not unlucky — it's your fear of failure. Unleash main character energy.",
  "You're not unlucky — silence the inner hater. Do it for the plot.",
  "You're not unlucky — silence the inner hater. Get dramatic with your ambition.",
  "You're not unlucky — silence the inner hater. Pretend you're in a montage.",
  "You're not unlucky — silence the inner hater. Today owes you nothing. Take it anyway.",
  "You're not unlucky — that's just the Wi-Fi talking. Become ungovernable.",
  "You're not unlucky — that's just the Wi-Fi talking. Get dramatic with your ambition.",
  "You're not unlucky — that's just the Wi-Fi talking. Get mad, then get moving.",
  "You're not unlucky — that's just the Wi-Fi talking. Today owes you nothing. Take it anyway.",
  "You're not unlucky — that's just the Wi-Fi talking. Unleash main character energy.",
];

const List<String> moreMotivationalQuotes = [
  "Outrun your past like it owes you money.",
  "You're not lazy, just too creative for mundane tasks.",
  "Wake up. Choose chaos. Organize it.",
  "Doubt is just a squatter in your brain—evict it.",
  "If they call you extra, charge them interest.",
  "You're not behind; you're in stealth mode.",
  "Get up and scare your potential into action.",
  "Your comfort zone called—it's getting evicted.",
  "Burnout isn't a trophy. Work smart, not to ashes.",
  "Slay your to-do list like it insulted your dog.",
  "Rise and shine? Nah. Rise and conquer.",
  "Be a menace to mediocrity.",
  "A plan is just rebellion with a calendar.",
  "Don't chase dreams—ambush them.",
  "Your future self is watching. Don't disappoint her.",
  "Perfection is a scam. Be consistently weird instead.",
  "Ignore the noise. Build your empire quietly.",
  "Monday blues? Paint it neon.",
  "Be the glitch in the matrix—on purpose.",
  "The limit isn't the sky. It's your Wi-Fi.",
  "Your vibe is the resume the universe reads.",
  "Break the cycle, not your spirit.",
  "Go feral—but with a spreadsheet.",
  "One person's 'too much' is another's inspiration.",
  "Grind like you're trying to escape a simulation.",
  "If it scares you, it might just be the way.",
];

const List<String> chaoticQuotes = [
  "Feral productivity starts with one unhinged to-do list.",
  "Delusional confidence is just confidence that hasn't been proven right yet.",
  "You don't need a plan. You need caffeine and vibes.",
  "You're not procrastinating—you're incubating brilliance.",
  "Become ungovernable. Start by making your bed.",
  "Why fit in when you can disrupt the entire ecosystem?",
  "Your chaos is your competitive advantage.",
  "You woke up today. That's the first victory. Now go commit a few more.",
  "Be the glitch in the system you want to see in the world.",
  "Productivity tip: pretend you're the main character in a redemption arc.",
  "Everything is made up and you can do what you want—within reason. Or not.",
  "Revenge arc starts now. Step one: hydrate.",
  "Your goals are scared of you. Good. Chase them anyway.",
  "You're one slightly unhinged idea away from greatness.",
  "Ignore the rules. Make your own. Break those too.",
  "Confidence isn't real. But act like it is until it becomes contagious.",
  "Stay soft. Destroy everything anyway.",
  "Your vibe today? Controlled chaos with high output.",
  "You are the storm in your own weather app.",
  "You're not behind. You're just charging up for a dramatic entrance.",
  "There are no stupid questions, only stupid people.",
];
